### PR TITLE
Move dependencies to peer dependencies

### PR DESCRIPTION
**Pull request by johnhaup**
## ✏️ Description

> Using the UI components (example: Inbox) breaks because react navigation and safe area context are dependencies in the SDK, so they get installed in the package's own node_modules (`node_modules/@iterable/react-native-sdk/node_modules`).  The makes the components look for navigation context and safe area context from an instance in its own node_modules, instead of the consumer's project.

- Removed react-hooks package (unused in SDK)
- Moved lint packages from `dependencies` to `devDependencies`
- Moved packages from `dependencies` to `peerDependencies`, using major versions as minimum

### CODE REVIEW

**Review by lposen — APPROVED** [review]

**Comment by lposen** [comment]
Approved.  Looks good to me.

**Comment by johnhaup** [comment]
This also address #596

**Comment by bhandanyan-nomad** [comment]
@lposen @johnhaup exciting change. I'd love to incorporate this into my project because I'm looking to upgrade `react-native-safe-area-context` from v4 to v5 and this change will allow me to avoid having two versions installed or needing to add a manual resolution to the version of my choosing.

Can you let me know if this will be available in a new release soon (ie this week) or not?

**Comment by alex-a-pereira** [comment]
thank you!!

**Pull request merged**
