### PR TITLE
Add setReadForMessage to Android bridge

### PR DESCRIPTION
**Pull request by rayzeller**
## ✏️ Description

Add `setReadForMessage` to Android bridge

image

### CODE REVIEW

**Comment by roninopf** [comment]
Hi @rayzeller, thanks for the PR, but we're fixing the message read state very soon. Was there a particular use for this you had that wasn't mentioned in this issue report? https://github.com/Iterable/react-native-sdk/issues/92

**Comment by rayzeller** [comment]
I think when `read` is integrated into an API call, it will allow us to refactor our code so that we don't need to use the above method.

However, right now `setReadForMessage` is only defined for iOS devices. Trying to use it on Android would cause our devices to crash. I went ahead and PR-ed the patch we made so this wouldn't be the case. I guess we could also skip this API altogether with `set(message, 'read', true)` or a similar call, but right now the Typescript for `setReadForMessage` is misleading.

**Comment by rayzeller** [comment]
Also @jehartzog and I work at the same company on a team of 3 engineers. Glad you're working on the issue ^_^. You have anything to add Eric?

**Comment by jehartzog** [comment]
Nothing to add. Glad to hear there may be plans to transfer `read` field support to the API, that will enable the use cases we originally planned on. I agree w/ merging this PR in the interim, as using it currently will cause crashes on Android devices.

**Comment by roninopf** [comment]
> I think when `read` is integrated into an API call, it will allow us to refactor our code so that we don't need to use the above method.
> 
> However, right now `setReadForMessage` is only defined for iOS devices. Trying to use it on Android would cause our devices to crash. I went ahead and PR-ed the patch we made so this wouldn't be the case. I guess we could also skip this API altogether with `set(message, 'read', true)` or a similar call, but right now the Typescript for `setReadForMessage` is misleading.

AH! Thank you. Another team member also informed me of this as well, I didn't realize this was happening since I usually work on the iOS bridge.

**Review by roninopf — APPROVED** [review]

**Pull request merged**
